CREATE DATABASE IF NOT EXISTS Rede_Social;
USE Rede_Social;

CREATE TABLE IF NOT EXISTS GRUPOS(
ID_GRUPO INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DESCRICAO TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS USUARIOS(
ID_USUARIO INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
SOBRENOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(45) NOT NULL);

CREATE TABLE IF NOT EXISTS POSTAGENS(
ID_POST INT PRIMARY KEY,
TEXTO TEXT NOT NULL,
IMAGEM BLOB,
DATA_HORA TIMESTAMP NOT NULL,
USUARIO INT,
CONSTRAINT USER_POST FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID_USUARIO));

CREATE TABLE IF NOT EXISTS COMENTARIOS(
ID_COMMENT INT PRIMARY KEY,
TEXTO TEXT NOT NULL,
DATA_HORA TIMESTAMP NOT NULL,
USUARIO INT,
POST INT,
CONSTRAINT USER_COMM FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID_USUARIO),
CONSTRAINT POST_COMM FOREIGN KEY(POST) REFERENCES POSTAGENS(ID_POST));

CREATE TABLE IF NOT EXISTS USUARIOS_GRUPOS(
SEGUIDOR INT,
GRUPO INT,
PRIMARY KEY(SEGUIDOR,GRUPO),
CONSTRAINT USER_GRUP FOREIGN KEY(SEGUIDOR) REFERENCES USUARIOS(ID_USUARIO),
CONSTRAINT GRUP_USER FOREIGN KEY(GRUPO) REFERENCES GRUPOS(ID_GRUPO));

CREATE TABLE IF NOT EXISTS SEGUIDORES_USUARIOS(
SEGUIDOR INT,
SEGUIDO INT,
PRIMARY KEY(SEGUIDOR,SEGUIDO),
CONSTRAINT USER_1 FOREIGN KEY(SEGUIDOR) REFERENCES USUARIOS(ID_USUARIO),
CONSTRAINT USER_2 FOREIGN KEY(SEGUIDO) REFERENCES USUARIOS(ID_USUARIO)
);

#ALTERANDO O TIPO E RESTRIÇÃO DAS COLUNAS
ALTER TABLE COMENTARIOS
MODIFY COLUMN USUARIO INT NOT NULL;

ALTER TABLE COMENTARIOS
MODIFY COLUMN POST INT NOT NULL;

-- TRUNCATE TABLE GRUPOS; #EXCLUI APENAS OS DADOS
-- DROP TABLE GRUPOS; #EXCLUI A TABELA INTEIRA
-- DROP SCHEMA REDESOCIAL; #EXCLUI TODO O SCHEMA
